config/routes.rb
Rails.application.routes.draw do
  resources :employeds
  root 'acta#index'

  get "pruba/:id", to: "acta#prueba", as: "pruba"

  get "acta_pdf/:id", to: "acta#acta_pdf", as: "acta_pdf"
  
  resources :tools
  resources :acta
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tool.rb
# == Schema Information
#
# Table name: tools
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  prince     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tool < ApplicationRecord
	has_many :items_tools
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1
  # PATCH/PUT /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tool_params
      params.require(:tool).permit(:name, :prince)
    end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_form.html.erb
<%= form_with(model: tool, local: true) do |form| %>
  <% if tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :prince %>
    <%= form.number_field :prince %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tools/edit.html.erb
<h1>Editing Tool</h1>

<%= render 'form', tool: @tool %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Tools</h1>
<br>
<table class="table" style="padding: ">
  <thead class="table-primary">
    <tr>
      <th>Name</th>
      <th>Prince</th>
      <th colspan="3"><%= link_to 'Nueva Herramienta', new_tool_path, class: "btn btn-primary", style: "float: right;"  %></th>
    </tr>
  </thead>

  <tbody>
    <% @tools.each do |tool| %>
      <tr>
        <td><%= tool.name %></td>
        <td><%= tool.prince %></td>
        <td>
          <%= link_to tool, class: "btn btn-primary", title: "Ver" do %>
             <i class="far fa-eye"></i>
          <% end -%>

          <%= link_to edit_tool_path(tool), class: "btn btn-primary", title: "Editar" do %>
            <i class="fas fa-pencil-alt"></i>
          <% end -%>

          <%= link_to  tool, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", title: "Elininar" do %>
            <i class="fas fa-trash-alt"></i>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tools/new.html.erb
<h1>New Tool</h1>

<%= render 'form', tool: @tool %>

<%= link_to 'Back', tools_path %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tool.name %>
</p>

<p>
  <strong>Prince:</strong>
  <%= @tool.prince %>
</p>

<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>