config/routes.rb
Rails.application.routes.draw do
  resources :employeds
  root 'acta#index'

  get "pruba/:id", to: "acta#prueba", as: "pruba"

  get "acta_pdf/:id", to: "acta#acta_pdf", as: "acta_pdf"
  
  resources :tools
  resources :acta
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employed.rb
# == Schema Information
#
# Table name: employeds
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  cedula     :integer
#  cargo      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Employed < ApplicationRecord
	has_many :actum
	#belongs_to :employed_one, :class_name => 'Employed'
	#belongs_to :employed_two, :class_name => 'Employed'
end

app/controllers/employeds_controller.rb
class EmployedsController < ApplicationController
  before_action :set_employed, only: [:show, :edit, :update, :destroy]

  # GET /employeds
  # GET /employeds.json
  def index
    @employeds = Employed.all
  end

  # GET /employeds/1
  # GET /employeds/1.json
  def show
  end

  # GET /employeds/new
  def new
    @employed = Employed.new
  end

  # GET /employeds/1/edit
  def edit
  end

  # POST /employeds
  # POST /employeds.json
  def create
    @employed = Employed.new(employed_params)

    respond_to do |format|
      if @employed.save
        format.html { redirect_to @employed, notice: 'Employed was successfully created.' }
        format.json { render :show, status: :created, location: @employed }
      else
        format.html { render :new }
        format.json { render json: @employed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employeds/1
  # PATCH/PUT /employeds/1.json
  def update
    respond_to do |format|
      if @employed.update(employed_params)
        format.html { redirect_to @employed, notice: 'Employed was successfully updated.' }
        format.json { render :show, status: :ok, location: @employed }
      else
        format.html { render :edit }
        format.json { render json: @employed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employeds/1
  # DELETE /employeds/1.json
  def destroy
    @employed.destroy
    respond_to do |format|
      format.html { redirect_to employeds_url, notice: 'Employed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employed
      @employed = Employed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employed_params
      params.require(:employed).permit(:name, :cedula, :cargo, :actum_id)
    end
end

app/helpers/employeds_helper.rb
module EmployedsHelper
end

app/views/employeds/_form.html.erb
<%= form_with(model: employed, local: true) do |form| %>
  <% if employed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employed.errors.count, "error") %> prohibited this employed from being saved:</h2>

      <ul>
      <% employed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form form-control" %>
  </div>
  <br>

  <div class="col-md-4">
    <%= form.label :cedula %><br>
    <%= form.number_field :cedula, class: "form form-control" %>
  </div>
  <br>

  <div class="col-md-4">
    <%= form.label :cargo %><br>
    <%= form.text_field :cargo, class: "form form-control" %>
  </div>
  <br>

  <div class="col-md-4">
    <%= form.submit "Guardar", class: "btn btn-info" %>
  </div>

<% end %>

app/views/employeds/edit.html.erb
<h1>Editing Employed</h1>

<%= render 'form', employed: @employed %>

<%= link_to 'Show', @employed %> |
<%= link_to 'Back', employeds_path %>

app/views/employeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Empleados</h1>
<br>
<table class="table">
  <thead class="table-primary">
    <tr>
      <th>Name</th>
      <th>Cedula</th>
      <th>Cargo</th>
      <th colspan="3"><%= link_to 'Nuevo Empleado', new_employed_path, class: "btn btn-primary", style: "float: right;" %></th>
    </tr>
  </thead>

  <tbody>
    <% @employeds.each do |employed| %>
      <tr>
        <td><%= employed.name %></td>
        <td><%= employed.cedula %></td>
        <td><%= employed.cargo %></td>

        <td>

          <%= link_to employed, class: "btn btn-primary", title: "Ver", style: "float: right; margin-left: 4px;" do %>
             <i class="far fa-eye"></i>
          <% end -%>

          <%= link_to edit_employed_path(employed), class: "btn btn-primary", title: "Editar", style: "float: right; margin-left: 4px;" do %>
            <i class="fas fa-pencil-alt"></i>
          <% end -%>

          <%= link_to  employed, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", title: "Elininar", style: "float: right; margin-left: 4px;" do %>
            <i class="fas fa-trash-alt"></i>
          <% end -%>
          
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/employeds/new.html.erb
<h1 align="center">Nuevo Empleado</h1>

<%= render 'form', employed: @employed %>

app/views/employeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employed.name %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @employed.cedula %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @employed.cargo %>
</p>


<%= link_to 'Edit', edit_employed_path(@employed) %> |
<%= link_to 'Back', employeds_path %>