config/routes.rb
Rails.application.routes.draw do
  resources :employeds
  root 'acta#index'

  get "pruba/:id", to: "acta#prueba", as: "pruba"

  get "acta_pdf/:id", to: "acta#acta_pdf", as: "acta_pdf"
  
  resources :tools
  resources :acta
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/acta_controller.rb
class ActaController < ApplicationController
  before_action :set_actum, only: [:show, :edit, :update, :destroy]

  # GET /acta
  # GET /acta.json
  def index
    @acta = Actum.all
  end

  # GET /acta/1
  # GET /acta/1.json
  def show

  end

  def acta_pdf
    @actum = Actum.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "formatos1",
          :template => 'acta/pdfs/formatos.pdf.erb',
          :layout => 'pdf.html.erb',
          :show_as_html => params[:debug].present?
      end
    end 
  end






  def prueba
    @tool = Tool.find(params[:id])

    render json: @tool
    
  end

  # GET /acta/new
  def new
    @actum = Actum.new
  end

  # GET /acta/1/edit
  def edit
  end

  # POST /acta
  # POST /acta.json
  def create
    @actum = Actum.new(actum_params)

    respond_to do |format|
      if @actum.save
        format.html { redirect_to @actum, notice: 'Actum was successfully created.' }
        format.json { render :show, status: :created, location: @actum }
      else
        format.html { render :new }
        format.json { render json: @actum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acta/1
  # PATCH/PUT /acta/1.json
  def update
    respond_to do |format|
      if @actum.update(actum_params)
        format.html { redirect_to @actum, notice: 'Actum was successfully updated.' }
        format.json { render :show, status: :ok, location: @actum }
      else
        format.html { render :edit }
        format.json { render json: @actum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acta/1
  # DELETE /acta/1.json
  def destroy
    @actum.destroy
    respond_to do |format|
      format.html { redirect_to acta_url, notice: 'Actum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actum
      @actum = Actum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actum_params
      params.require(:actum).permit(:fecha, :description, :signature_delivery, :signature_requests, :employed_id, items_tools_attributes: [:id, :tools_id, :actum_id, :quantity, :unit_prince, :total_prince, :firm, :_destroy])
    end
end

app/helpers/acta_helper.rb
module ActaHelper
end

app/views/acta/edit.html.erb
<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-table"></i>
      Editar Acta de Entrega</div>
    <div class="card-body">
      <%= render 'form', actum: @actum %>
  </div>
</div>

app/views/acta/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Acta</h1>
<br>
<table class="table" style="padding: ">
  <thead class="table-primary">
    <tr >
      <th>Fecha</th>
      <th>observaciones</th>
      <th>Entrego</th>
      <th>Recibio</th>
      <th colspan="3"><%= link_to 'Nueva Acta', new_actum_path, class: "btn btn-primary", style: "float: right;" %></th>
    </tr>
  </thead>

  <tbody>
    <% @acta.each do |actum| %>
      <tr>
        <td><%= get_only_date(actum.fecha) %></td>
        <td><%= actum.description %></td>
        <td><%= actum.employed.name %></td>
        <td><%= actum.employed.name%></td>

        <td style="float: right;">

          <%= link_to actum, class: "btn btn-primary", title: "Ver" do %>
             <i class="far fa-eye"></i>
          <% end -%>

          <%= link_to acta_pdf_path(actum.id, :format => "pdf"), target:"_blank", class: "btn btn-info", title: "Generar Pdf" do%>
            <i class="far fa-file-pdf"></i>
          <% end -%>

          <%= link_to edit_actum_path(actum), class: "btn btn-primary", title: "Editar" do %>
            <i class="fas fa-pencil-alt"></i>
          <% end -%>

          <%= link_to  actum, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", title: "Elininar" do %>
            <i class="fas fa-trash-alt"></i>
          <% end -%>
          
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<style type="text/css">
  td img{
    width: 56px;
  }
</style>

app/views/acta/new.html.erb
<div class="card mb-3">
  <div class="card-header">
    <i class="fas fa-table"></i>
      Nueva Acta de Entrega</div>
    <div class="card-body">
      <%= render 'form', actum: @actum %>
  </div>
</div>

app/views/acta/show.html.erb
<div class="container">	
    <h1 align="center">Acta de Entrega</h1>

    <p align="center"> 
      <%= get_only_date(@actum.fecha) %>, se hace entrega al señor <%= @actum.employed.name %>, identificado con CC No. <%= @actum.employed.cedula %>, de los siguientes elementos de Trabajo
    </p>

    <div class="col-md-12 col-md-offset-8" style="margin-bottom: 100px;">
        <table border="1px" align="center">
          <thead >
            <tr>
              <th style="width: 60px !important;">N° Item</th>
              <th style="width: 200px !important;">Descripcion</th>
              <th style="width: 50px !important;">Cantidad</th>
            </tr>
          </thead>


          <tbody>
            <% @actum.items_tools.each_with_index do |tool, posicion| %>
              <tr>
                <td align="center"><%= posicion + 1 %></td>
                <td align="center"><%= tool.tools.name %></td>
                <td><%= tool.quantity   %></td>
              </tr>
            <% end -%>
          </tbody>

        </table>
    </div>

    <div class="col-md-12 col-md-offset-8">
        <table align="center" id="items">

          <tbody>
              <tr>
                <td class="td" style=" border-bottom: 1px solid black;">
                  <b><p>ENTREGA:</p></b>


                  <img src="data:image/pnd;base64,<%= @actum.signature_delivery%>" alt="">
                  <b><small><%= @actum.employed.cargo %> de planta dnuba<br>
                    <%= @actum.employed.name %>
                  </small></b>
                </td>
                <td class="espacio"></td>
                <td class="td" style=" border-bottom: 1px solid black;">
                  <b><p>RECIBE:</p></b>
                  
                <img src="data:image/pnd;base64,<%= @actum.signature_requests%>" alt="">
                  <b><small><%= @actum.employed.cargo %> #1<br>
                    <%= @actum.employed.name %>
                  </small></b>
                </td>
              </tr>
          </tbody>

        </table>
    </div>

  </div>
</div>


<style type="text/css">
	h1{
		margin-bottom: 40px;
		margin-top: 40px;
	}

  p{
    margin-bottom: 100px;
  }

  #items{
    width: 100% !important;
  }

  .td{
    width: 250px !important;
    height: 250px !important;
    padding: 10px !important;
  }

  .td p{
    position: relative;
    top: -60px !important;
    font-size: 20px;
  }

  .td small{
    position: relative;
    top: 95px !important;
    padding-left: 0px !important;
    text-align: center;
  }

  .td img{
    width: 300px;
  }

  .espacio{
    width: 170px !important;
  }
</style>